services:
  svc_0:
    command: --name=svc_0 --zipkin=zipkin:9411 --msg-size=100 --msg-time=100 --load=0.35
      --mem=0 svc_2
    container_name: svc_0
    depends_on:
    - svc_2
    image: adalrsjr1/microservice
    ports:
    - 8080:8080
  svc_1:
    command: --name=svc_1 --zipkin=zipkin:9411 --msg-size=100 --msg-time=100 --load=0.35
      --mem=0 svc_4 svc_6
    container_name: svc_1
    depends_on:
    - svc_4
    - svc_6
    image: adalrsjr1/microservice
  svc_2:
    command: --name=svc_2 --zipkin=zipkin:9411 --msg-size=100 --msg-time=100 --load=0.35
      --mem=0 svc_1
    container_name: svc_2
    depends_on:
    - svc_1
    image: adalrsjr1/microservice
  svc_3:
    command: --name=svc_3 --zipkin=zipkin:9411 --msg-size=100 --msg-time=100 --load=0.35
      --mem=0 svc_8 svc_9
    container_name: svc_3
    depends_on:
    - svc_8
    - svc_9
    image: adalrsjr1/microservice
  svc_4:
    command: --name=svc_4 --zipkin=zipkin:9411 --msg-size=100 --msg-time=100 --load=0.35
      --mem=0 svc_3 svc_5
    container_name: svc_4
    depends_on:
    - svc_3
    - svc_5
    image: adalrsjr1/microservice
  svc_5:
    command: '--name=svc_5 --zipkin=zipkin:9411 --msg-size=100 --msg-time=100 --load=0.35
      --mem=0 '
    container_name: svc_5
    depends_on: []
    image: adalrsjr1/microservice
  svc_6:
    command: '--name=svc_6 --zipkin=zipkin:9411 --msg-size=100 --msg-time=100 --load=0.35
      --mem=0 '
    container_name: svc_6
    depends_on: []
    image: adalrsjr1/microservice
  svc_7:
    command: '--name=svc_7 --zipkin=zipkin:9411 --msg-size=100 --msg-time=100 --load=0.35
      --mem=0 '
    container_name: svc_7
    depends_on: []
    image: adalrsjr1/microservice
  svc_8:
    command: --name=svc_8 --zipkin=zipkin:9411 --msg-size=100 --msg-time=100 --load=0.35
      --mem=0 svc_7
    container_name: svc_8
    depends_on:
    - svc_7
    image: adalrsjr1/microservice
  svc_9:
    command: '--name=svc_9 --zipkin=zipkin:9411 --msg-size=100 --msg-time=100 --load=0.35
      --mem=0 '
    container_name: svc_9
    depends_on: []
    image: adalrsjr1/microservice
version: '3'
