version: '3'

services:
  shop:
    image: adalrsjr1/microservice
    container_name: front-end
    ports:
      - 8080:8080
    depends_on:
      - back-end-1
      - back-end-2
    command: --name=front-end --x=2 --y=2 --msg-size=128 --msg-time=1 --a=1 --b=-234 --c=4 --d=0.1 --e=2.5 --f=-7 --g=3 --h=12 --zipkin=zipkin:9411 back-end-1 back-end-2
    #command: --name=front-end --msg-size=128 --msg-time=10 --load=0.33 --mem=1 --zipkin=zipkin:9411 back-end-1 back-end-2

  back-end-1:
    image: adalrsjr1/microservice
    container_name: back-end-1
    depends_on:
      - back-end-3
      - back-end-4
    command: --name=back-end-1 --x=2 --y=2 --msg-size=256 --msg-time=1 --a=1 --b=-234 --c=4 --d=0.1 --e=2.5 --f=-7 --g=3 --h=12 --zipkin=zipkin:9411 back-end-3 back-end-4
    #command: --name=back-end-1 --msg-size=256 --msg-time=30 --zipkin=zipkin:9411 back-end-3 back-end-4

  back-end-2:
    image: adalrsjr1/microservice
    container_name: back-end-2
    depends_on:
      - back-end-5
    command: --name=back-end-2 --x=2 --y=2 --msg-size=256 --msg-time=30 --a=1 --b=-234 --c=4 --d=0.1 --e=2.5 --f=-7 --g=3 --h=12 --zipkin=zipkin:9411 back-end-5
    #command: --name=back-end-2 --msg-size=256 --msg-time=30 --zipkin=zipkin:9411 back-end-5

  back-end-3:
    image: adalrsjr1/microservice
    container_name: back-end-3
    command: --name=back-end-3 --x=2 --y=2 --msg-size=256 --msg-time=30 --a=1 --b=-234 --c=4 --d=0.1 --e=2.5 --f=-7 --g=3 --h=12 --zipkin=zipkin:9411
    #command: --name=back-end-3 --msg-size=256 --msg-time=30 --zipkin=zipkin:9411

  back-end-4:
    image: adalrsjr1/microservice
    container_name: back-end-4
    command: --name=back-end-4 --x=2 --y=2 --msg-size=256 --msg-time=30 --a=1 --b=-234 --c=4 --d=0.1 --e=2.5 --f=-7 --g=3 --h=12 --zipkin=zipkin:9411
    #command: --name=back-end-4 --msg-size=256 --msg-time=30 --zipkin=zipkin:9411

  back-end-5:
    image: adalrsjr1/microservice
    container_name: back-end-5
    command: --name=back-end-5 --x=2 --y=2 --msg-size=256 --msg-time=30 --a=1 --b=-234 --c=4 --d=0.1 --e=2.5 --f=-7 --g=3 --h=12 --zipkin=zipkin:9411
    #command: --name=back-end-5 --msg-size=256 --msg-time=30 --zipkin=zipkin:9411

