{
 "title": "smarttuning",
 "time": { "from": "2020-11-22T01:38:40.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "container_cpu_usage_seconds_total"
   },
   {
    "name": "time_interval_m",
    "query": "30s,1m,100s,200s,5m,6m,400s,10m,15m,20m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "prod_podname",
    "query": "container_cpu_usage_seconds_total"
   },
   {
    "name": "train_podname",
    "query": "container_cpu_usage_seconds_total"
   }
  ]
 },
 "panels": [
  {
   "title": "Queued Requests Connection Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vendor_connectionpool_queuedRequests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "PROD {{datasource}}"
    },
    {
     "expr": "sum(rate(vendor_connectionpool_queuedRequests_total{pod=~\"$train_podname-.*\", name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "TRAIN {{datasource}}"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(vendor_connectionpool_managedConnections{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "PROD {{datasource}}"
    },
    {
     "expr": "sum(avg_over_time(vendor_connectionpool_managedConnections{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "TRAIN {{datasource}}"
    }
   ]
  },
  {
   "title": "Connection Pool Waiting Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(vendor_connectionpool_waitTime_total_seconds{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by( datasource) / sum(rate(vendor_connectionpool_queuedRequests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "PROD {{datasource}}"
    },
    {
     "expr": "sum(avg_over_time(vendor_connectionpool_waitTime_total_seconds{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by( datasource) / sum(rate(vendor_connectionpool_queuedRequests_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "TRAIN {{datasource}}"
    }
   ]
  },
  {
   "title": "Thread pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(vendor_threadpool_activeThreads{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD thread pool"
    },
    {
     "expr": "sum(avg_over_time(vendor_threadpool_activeThreads{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN thread pool"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\".*nginx.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "gw"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$prod_podname.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "prod+train"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (pod)"
    }
   ]
  },
  {
   "title": "requests / $",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / ((0.0535*sum(rate(container_cpu_usage_seconds_total{id=~\".kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))+0.013375*sum( max_over_time(container_memory_working_set_bytes{id=~\".kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", container!=\"\"}[$time_interval_m])) / 2^20)/2)",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / ((0.0535*sum(rate(container_cpu_usage_seconds_total{id=~\".kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))+0.013375*sum( max_over_time(container_memory_working_set_bytes{id=~\".kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container!=\"\"}[$time_interval_m])) / 2^20)/2)",
     "legendFormat": "TRAIN $train_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (pod) / ((0.0535*sum(rate(container_cpu_usage_seconds_total{id=~\".kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (pod)+0.013375*sum( max_over_time(container_memory_working_set_bytes{id=~\".kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", container!=\"\"}[$time_interval_m])) by (pod) / 2^20)/2)"
    }
   ]
  },
  {
   "title": "requests / MB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / (sum( max_over_time(container_memory_working_set_bytes{id=~\".kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container!=\"\"}[$time_interval_m]))/2^20)",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / (sum( max_over_time(container_memory_working_set_bytes{id=~\".kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container!=\"\"}[$time_interval_m]))/2^20)",
     "legendFormat": "TRAIN $train_podname"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".kubepods.*\",pod=~\"$prod_podname.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "prod + train"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".kubepods.*\",pod=~\".*-db-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "database"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", container!=\"\"}[$time_interval_m])) ",
     "legendFormat": "PROD"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container!=\"\"}[$time_interval_m]))",
     "legendFormat": "TRAIN"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".kubepods.*\",pod=~\"$prod_podname.*\",name!~\".*POD.*\", container!=\"\"}[$time_interval_m]))",
     "legendFormat": "prod + train"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".kubepods.*\",pod=~\".*-db-.*\",name!~\".*POD.*\", container!=\"\"}[$time_interval_m]))",
     "legendFormat": "database"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum( rate(smarttuning_http_processtime_seconds_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum( rate(smarttuning_http_processtime_seconds_count{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (pod) / sum( rate(smarttuning_http_processtime_seconds_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (pod)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[4|5]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) /sum( rate(smarttuning_http_requests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[4|5]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) /sum( rate(smarttuning_http_requests_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    }
   ]
  }
 ]
}